$(document).ready(function(){
  $(".opt1").click(function(){
    $(".scroll-alert-msg").show();
  });
  $(".opt2").click(function(){
    $(".scroll-alert-msg").show();
  });
  $(".opt3").click(function(){
    $(".scroll-alert-msg").show();
  });
  $(".opt4").click(function(){
    $(".scroll-alert-msg").show();
  });
});
